import Navbar from '../components/Navbar';

export default async function About() {
  const revalidatedData = await fetch("https://gist.githubusercontent.com/serapagranchose/bc9b8dd8959b352699aa258a7924b729/raw/e40b98bf9fc5a42a4df9baec46a3bbf24302eda0/resume.json", {
    next: { revalidate: 10 },
  }).then(results => {
    return results.json();
  })

  return (
    <>
      <Navbar/>
      <main className="pt-28 p-2 flex flex-row min-h-screen justify-between">
        <div>
          <h2 className="text-2xl">WHO I AM</h2>
          <p>
            HI! I'M SÉRAPHIN PERROT - FULL STACK DEVELOPER, PIXEL ARTIST.<br/>
          </p>
          <p className="pt-2">
            MY PASSION FOR COMPUTER DEVELOPMENT AND PIXEL ART GOES BACK TO WHEN I WAS A KID, THANKS TO MY FAMILY;<br/>
            MY GRANDFATHER WAS A PROFESSOR OF INDUSTRIAL AUTOMATION AND TECHNOLOGY, AND MY MOM HAD OLD CONSOLES THAT I PLAYED ON (TOO) OFTEN, LIKE THE ICONIC GAMEBOY.<br/>
          </p>
          <p className="pt-2">
            GROWING UP IN THE 2000S, NOSTALGIC FOR MY PARENTS AND COMPUTERS, I WITNESSED THE EXPONENTIAL EVOLUTION OF TECHNOLOGY UP CLOSE, AND THIS HAD A PROFOUND EFFECT ON ME AS A HUMAN BEING.<br/>
            I WAS SOON DRAWN TO COMPUTER DEVELOPMENT, DEVELOPING MY OWN GAMES FROM THE AGE OF 9.<br/>
            I'M CONSTANTLY ON THE LOOKOUT FOR NEW TECHNOLOGIES, BECAUSE I'M A CURIOUS PERSON.<br/>
          </p>
          <h2 className="text-2xl pt-6">EDUCATION</h2>
          <p>
            NATURALLY I WANTED TO MOVE INTO IT AS SOON AS POSSIBLE, SO I DECIDED TO TAKE A SCIENCE OF TECHNOLOGY AND SUSTAINABLE DEVELOPMENT MAJORING IN INFORMATION AND DIGITAL SYSTEMS AT THE LYCÉE ANDRÉE MALRAUX IN BÉTHUNE.<br/>
            SEEING THAT THE VERY THEORETICAL SCHOOL SYSTEM WAS NOT SUITED TO LEARNING TECHNOLOGY, WHICH WAS EVOLVING VERY RAPIDLY, MAKING THE LESSONS AND TECHNOLOGIES STUDIED QUICKLY OBSOLETE,<br/>
            I THEN WENT TO EPITECH LILLE TO DO A MASTER'S DEGREE IN COMPUTER ENGINEERING.<br/>
            EPITECH TAUGHT ME HOW TO LEARN, HOW TO FACE UP TO THE FEARS THAT PREVENTED ME FROM LEARNING.<br/>
            IT'S NORMAL TO BE A BEGINNER, THE TRICK IS TO RISE TO THE CHALLENGE, NO MATTER HOW DIFFICULT IT IS, OR HOW LITTLE GUIDANCE OR DOCUMENTATION YOU HAVE.
          </p>
          <h2 className="text-2xl pt-6">HOBBIES</h2>
          <p>
            SINCE I SPEND MOST OF MY DAYS DEVELOPING IN FRONT OF A SCREEN WHEN I WANT TO CLEAR MY HEAD, I LIKE TO REPAIR AND USE OLD ANALOG EQUIPMENT.<br/>
            AN OLD POLAROID, A RADIO CASSETTE OR EVEN A MOPED, ANYTHING GOES.<br/>
            I READ BOOKS, WRITE IN MY DIARY AND PLAY MUSIC.<br/>
            IN TERMS OF SPORTS, I SKATEBOARD AND GO TO THE GYM.<br/>
            OH AND I PLAY A CARD GAME CALLED "MAGIC: THE GATHERING".<br/>
          </p>
          <h2 className="text-2xl pt-6">LANGUAGE</h2>
          <p>
            I HAVE ALWAYS LOVED MUSIC AND SINCE I WAS LITTLE MY DAYS WERE PUNCTUATED WITH ENGLISH MUSIC.<br/>
            WITH THE EMERGENCE OF SOCIAL NETWORKING AND MY PASSION FOR IT, I QUICKLY REALIZED THAT MASTERING ENGLISH HAD TO BE ONE OF MY STRONG POINTS.<br/>
            I STUDIED SPANISH FROM SECONDARY SCHOOL TO HIGH SCHOOL FOR 5 YEARS, I ESTIMATE MY LEVEL AT B1 BUT I INTEND TO IMPROVE IN THE FUTURE.<br/>
            I WAS ABLE TO PASS A TOEIC EQUIVALENT AT EPITECH WITH A SCORE OF 795, WHICH ENABLED ME TO GO TO SOUTH KOREA AND MEET MANY INTERNATIONAL CONNECTIONS, SUCH AS MY SPANISH PARTNER.<br/>
          </p>
        </div>
      </main>
    </>
  );
}
